export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST'
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS'
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE'

export const DETAIL_ITEM_REQUEST = 'DETAIL_ITEM_REQUEST'
export const DETAIL_ITEM_SUCCESS = 'DETAIL_ITEM_SUCCESS'
export const DETAIL_ITEM_FAILURE = 'DETAIL_ITEM_FAILURE'

export const CREATE_ITEM_REQUEST = 'CREATE_ITEM_REQUEST'
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS'
export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE'

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE'

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST'
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS'
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE'

export const PAGINATION_ITEM_REQUEST = 'PAGINATION_ITEM_REQUEST'
export const PAGINATION_ITEM_SUCCESS = 'PAGINATION_ITEM_SUCCESS'
export const PAGINATION_ITEM_FAILURE = 'PAGINATION_ITEM_FAILURE'

export const SEARCH_PAGINATION_ITEM_REQUEST = 'SEARCH_PAGINATION_ITEM_REQUEST'
export const SEARCH_PAGINATION_ITEM_SUCCESS = 'SEARCH_PAGINATION_ITEM_SUCCESS'
export const SEARCH_PAGINATION_ITEM_FAILURE = 'SEARCH_PAGINATION_ITEM_FAILURE'

export const CLEAR_ITEM = 'CLEAR_ITEM'

export const LIMIT = 6